name: Deploy to GCS

on:
  push:
    branches:
      - sdx

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/checkout@v1
        name: Uses Node.js ${{ matrix.node-version }}

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        id: build
        env:
          NODE_ENV: development
        run: |
          npm install
          npm run build

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Upload build files
        id: "upload-files"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "dist"
          destination: "sspa-brownbag/navbar/${{steps.commit.outputs.hash}}"
          parent: false

      - name: Update importmap
        run: curl -d '{ "service":"@sspa-brownbag/navbar","url":"https://storage.googleapis.com/sspa-brownbag/navbar/${{steps.commit.outputs.hash}}/sspa-brownbag-navbar.js" }' -X PATCH http://104.196.136.89:5000/services\?env=test -H "Accept:application/json" -H "Content-Type:application/json"
